import = [
  "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
]

[font]
size = 8
# normal = { family = "FiraMono", style = "" }
normal = { family = "Monocraft", style = "" }

[env]
TERM = "xterm-256color"
